# Generated by Django 6.0.3 on 2026-03-30 04:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_alter_design_image_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.TextField(default='not provided'),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'design')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'design')},
        ),
    ]
